global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using CryptoSim_Lib.Enums;
global using CryptoSim_Lib.Models;
